name: BlockSeats
version: '${project.version}'
main: mc.thejsuser.blockseats.BlockSeats
api-version: 1.18
authors: [ TheJsUser ]
description: Allows players of the server to esasily turn stairs and slabs into chairs they can sit on.
